### ISSUE TITLE
Pressing the All Done button will not return user to list of entries when accessing a form entry via URL

### ISSUE THREAD

**Issue by jnip** [jegelstaff/formulize#178] opened 2015-02-08 04:15 UTC
The following URL is an example of accessing the second entry of the first form: http://localhost/formulize/modules/formulize/index.php?fid=1&ve=2

If a form entry is accessed via URL, clicking on the buttons "Save and Leave" or "All Done" will not return the user to the list of entries view.

Daniel suggested removing those buttons (if a user accesses the form entry in such a manner).

**Comment by eikonos** [comment] 2015-02-16 06:58
The issue is that if you access a data-entry view via the url, then there's no list view assigned to return to, so those buttons cannot return. They could send you to the default list view for the form instead.

**Comment by jnip** [comment] 2015-03-02 14:13
#193

**Closed** 2015-03-13 21:58 UTC
