### ISSUE TITLE
{BLANK} filter not working with radio button fields

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#405] opened 2024-01-08 20:44 UTC
I'm encountering similar issue as #341 with radio button on list screen after upgrading to version 7.21. It is working fine with checkboxes but not Y/N or regular radio buttons.

> Error: could not count master results.
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 ) )' at line 1

With the last clause being
>  ( main.element_handle ='1' or AND main.element_handle IS NOT NULL 1 )

**Comment by jegelstaff** [comment] 2024-02-10 07:19
Issue was caused by using alternative database values for radio buttons, different from the user sees in the form, and also using the same user-facing values from the form in the list. Using the DB values in the list worked OK. But using the user-facing values in the list (and in essence keeping the DB values just for the DB) leads to the issue.

The issue is fixed in commit 3b31f5f9337aad8178da522bb39573ae94c68992 and see https://www.php.net/manual/en/function.strstr.php#128207 for the explanation of the problem (PHP 8 related).

**Closed by jegelstaff** 2024-02-10 07:19 UTC
